<p align="center">
  <a href="https://imc.uc.cl" target="_blank">
    <img src="attachment:image.png" alt="IMC" width="220">
  </a>
</p>

# IMT 2200 - Introducción a Ciencia de Datos
**Pontificia Universidad Católica de Chile**<br>
**Instituto de Ingeniería Matemática y Computacional**<br>
**Profesor:** Rodrigo A. Carrasco <br>
---

## Tarea 04 – Aprendizaje automático

- **Fecha de Entrega:** 13 de noviembre de 2025, a las 23:59.
- **Fecha de publicación**: 30 de octubre de 2025.
- **Formato de entrega:** Notebook ejecutado y comentado (`.ipynb`) en el módulo de Tarea 04 habilitado en Canvas.

## Instrucciones

- Esta Tarea debe desarrollarse de manera totalmente *individual*, de acuerdo a lo establecido en la sección de Integridad Académica en el programa del curso.
- La Tarea debe ser desarrollada en lenguaje de programación Python y la entrega en formato Jupyter Notebook.
- El desarrollo del Notebook debe ser claro y ordenado, incluyendo anotaciones (markdown) y comentarios que permitan seguir fácilmente el código y los pasos implementados a los correctores, y siguiendo buenas prácticas de programación. La presentación y claridad del notebook y código forman parte de la evaluación de la tarea.
- Notebook **autocontenible** que:
   - Ejecute sin errores todas las celdas.
  - Contenga tanto el código como los comentarios y explicaciones necesarias.
  - Incluya visualizaciones claras y correctamente etiquetadas.
- No se aceptarán notebooks con celdas rotas o que dependan de rutas externas no indicadas en la tara.

- Deben hacer sus consultas y comentarios sobre la Tarea a traves del canal de Tareas en eo del curso en Canvas.os.
cteriza.

## 1. Objetivos

- Aplicar los conceptos iniciales de manejo de datos y análisis exploratorio vistos en clases.
- Practicar la lectura, limpieza y manipulación de datos en Python.
- Desarrollar habilidades para visualizar y describir patrones y tendencias en conjuntos de datos reales.
- Fomentar la capacidad de comunicar resultados de forma clara y fundamentada.

### 1.1 Objetivo educacional

Esta Tarea tiene como objetivo que los estudiantes desarrollen la capacidad de manejar algunas de las librerías centrales para el desarrollo de Ciencia de Datos, con foco en la lectura y exploración de datos. 

### 1.2 Pregunta de ciencia de datos

Esta tarea tendrá como objetivo crear un predictor que determine el éxito o fracaso de una expedición a distintas montañas del Himalayas según datos del montañista y de la expedición. Vamos a responder a la pregunta de qué tan bien pueden atributos como año, estación, montaña, edad del montañista, entre otros, predecir el éxito o fracaso de una expedición.

### 1.3 Recomendaciones
- Utiliza las librerías sugeridas en el notebook o justifica brevemente si incorporas otras.
- Revisa que todas las celdas se ejecuten en orden, desde el inicio, sin errores.
- Comenta tu código para explicar qué hace cada sección relevante.
- Asegúrate de que las visualizaciones sean fáciles de interpretar y tengan títulos y etiquetas adecuados.

## 2. Datos

[The Himalayan Database](https://www.himalayandatabase.com/) consiste en una colección de registros de expediciones en la cordillera del Himalaya. Esta contiene información detallada de las cimas más altas del mundo, junto con miles de expediciones realizadas desde 1905 hasta 2024 e información de cada uno de los/las montañistas que han participado en ellas. (El dataset que utilizaremos fue extraído desde: https://mavenanalytics.io/data-playground/himalayan-expeditions)

Descargue el archivo `Himalayan+Expeditions.zip` disponible en el repositorio del curso. Como puede ver, esta información está separada en varios archivos `.csv`. Deberá utilizar las herramientas aprendidas durante el curso para juntar esta información, procesarla y crear un predictor que determine el éxito de una subida.

**Recomendación**: Puede revisar el archivo `himalayan_data_dictionary.csv` para saber el significado de cada una de las columnas de la base de datos.

### 2.1 Librerías

Para esta tarea puede utilizar cualquiera de las librerías previamente utilizadas en el curso. Puede agregar otras si lo estima conveniente para el desarrollo de la Tarea.

In [292]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import plotly.express as px
# ...agreuge otras librerías si lo considera relevante

## 3. Carga y limpieza (1 punto)

### 3.1 DataFrame unificado (0.2 pts)

Inspeccione los atributos de cada dataset y extraiga la siguiente información de ellos:

1. Información de las montañas:
    * ID de la cima (`peakid`)
    * Nombre común de la montaña (`pkname`)
    * Altura (m) (`heightm`)
    * Cantidad de expediciones exitosas (`success_exp`)
    * Cantidad de expediciones fallidas (`failed_exp`)

2. Información de las expediciones:
    * ID de la expedición (`expid`)
    * Año (`year`)
    * Estación del año (`season`)

3. Información de los montañistas:
    * ID del miembro (`memid`)
    * Sexo (`sex`)
    * Año de nacimiento (`yob`)
    * Nacionalidad (`citizen`)
    * Completó la expedición exitosamente (`msuccess`)

Genere un único DataFrame con todos estos atributos, donde cada fila represente el ascenso de un/a montañista en una expedición. (Ojo que esto no necesariamente significa que cada fila será una persona diferente: si una persona escaló dos cumbres distintas en dos expediciones, esta debería aparecer en su DataFrame como dos filas separadas.)

In [293]:
exped = pd.read_csv("exped.csv")

exped.columns

/tmp/ipykernel_1385/3619914720.py:1: DtypeWarning: Columns (8,18,19) have mixed types. Specify dtype option on import or set low_memory=False.
  exped = pd.read_csv("exped.csv")

Index(['expid', 'peakid', 'year', 'season', 'host', 'route1', 'route2',
       'route3', 'route4', 'nation', 'leaders', 'sponsor', 'success1',
       'success2', 'success3', 'success4', 'ascent1', 'ascent2', 'ascent3',
       'ascent4', 'claimed', 'disputed', 'countries', 'approach', 'bcdate',
       'smtdate', 'smttime', 'smtdays', 'totdays', 'termdate', 'termreason',
       'termnote', 'highpoint', 'traverse', 'ski', 'parapente', 'camps',
       'rope', 'totmembers', 'smtmembers', 'mdeaths', 'tothired', 'smthired',
       'hdeaths', 'nohired', 'o2used', 'o2none', 'o2climb', 'o2descent',
       'o2sleep', 'o2medical', 'o2taken', 'o2unkwn', 'othersmts', 'campsites',
       'accidents', 'achievment', 'agency', 'comrte', 'stdrte', 'primrte',
       'primmem', 'primref', 'primid', 'chksum'],
      dtype='object')

In [294]:
himalayan = pd.read_csv("himalayan_data_dictionary.csv")

himalayan.columns

Index(['Table', 'Field', 'Description'], dtype='object')

In [295]:
members = pd.read_csv("members.csv")

members.columns

#en el enunciado dice memid y no membid, como se parece se asume que es un error , lo mismo con myear

/tmp/ipykernel_1385/2744021632.py:1: DtypeWarning: Columns (34) have mixed types. Specify dtype option on import or set low_memory=False.
  members = pd.read_csv("members.csv")

Index(['expid', 'membid', 'peakid', 'myear', 'mseason', 'fname', 'lname',
       'sex', 'yob', 'citizen', 'status', 'residence', 'occupation', 'leader',
       'deputy', 'bconly', 'nottobc', 'support', 'disabled', 'hired', 'sherpa',
       'tibetan', 'msuccess', 'mclaimed', 'mdisputed', 'msolo', 'mtraverse',
       'mski', 'mparapente', 'mspeed', 'mhighpt', 'mperhighpt', 'msmtdate1',
       'msmtdate2', 'msmtdate3', 'msmttime1', 'msmttime2', 'msmttime3',
       'mroute1', 'mroute2', 'mroute3', 'mascent1', 'mascent2', 'mascent3',
       'mo2used', 'mo2none', 'mo2climb', 'mo2descent', 'mo2sleep',
       'mo2medical', 'mo2note', 'death', 'deathdate', 'deathtime', 'deathtype',
       'deathhgtm', 'deathclass', 'msmtbid', 'msmtterm', 'hcn', 'mchksum'],
      dtype='object')

In [296]:
peaks_exp = pd.read_csv("peaks_with_exp.csv")

peaks_exp.columns

Index(['peakid', 'pkname', 'pkname2', 'location', 'heightm', 'heightf',
       'himal', 'region', 'open', 'unlisted', 'trekking', 'trekyear',
       'restrict', 'phost', 'pstatus', 'pyear', 'pseason', 'pmonth', 'pday',
       'pexpid', 'pcountry', 'psummiters', 'psmtnote', 'failed_exp',
       'success_exp'],
      dtype='object')

In [297]:
peaks = pd.read_csv("peaks.csv")

peaks.columns

Index(['peakid', 'pkname', 'pkname2', 'location', 'heightm', 'heightf',
       'himal', 'region', 'open', 'unlisted', 'trekking', 'trekyear',
       'restrict', 'phost', 'pstatus', 'pyear', 'pseason', 'pmonth', 'pday',
       'pexpid', 'pcountry', 'psummiters', 'psmtnote'],
      dtype='object')

In [298]:
exped_c = exped[["peakid","expid","year","season"]]
members_c = members[["peakid","expid","membid","myear","sex","yob","citizen","msuccess"]]
peaks_exp_c = peaks_exp[["peakid","pkname","heightm","success_exp","failed_exp"]]
peaks_c = peaks[["peakid","pkname","heightm"]]

In [299]:
display(exped_c.head())
display(members_c.head())
display(peaks_exp_c.head())
display(peaks_c.head())

  peakid      expid  year  season
0   ANN2  ANN260101  1960  Spring
1   ANN2  ANN269301  1969  Autumn
2   ANN2  ANN273101  1973  Spring
3   ANN2  ANN278301  1978  Autumn
4   ANN2  ANN279301  1979  Autumn

  peakid      expid  membid  myear sex     yob    citizen  msuccess
0   AMAD  AMAD01101       2   2001   M  1972.0  Australia     False
1   AMAD  AMAD01101       1   2001   M  1968.0  Australia     False
2   AMAD  AMAD01101       3   2001   M  1960.0  Australia     False
3   AMAD  AMAD01101       4   2001   M  1966.0  Australia     False
4   AMAD  AMAD01101       5   2001   F  1970.0  Australia     False

  peakid         pkname  heightm  success_exp  failed_exp
0   ACHN         Aichyn     6055            2           1
1   AMAD     Ama Dablam     6814         1123         453
2   AMOT       Amotsang     6393            1           2
3   AMPG  Amphu Gyabjen     5630            3           1
4   AMPH        Amphu I     6740            1           1

  peakid         pkname  heightm
0   ACHN         Aichyn     6055
1   AMAD     Ama Dablam     6814
2   AMOT       Amotsang     6393
3   AMPG  Amphu Gyabjen     5630
4   AMPH        Amphu I     6740

In [300]:
df_1 = pd.merge(members_c , exped_c, on=["peakid","expid"])
df_2 = pd.merge(df_1 , peaks_exp_c, on=["peakid"])

df_2 = df_2.rename(columns={"membid" : "memid"}) 

df_unificado = df_2[[
    "peakid" , "pkname" , "heightm" , "expid" , "year" ,
    "season" , "memid" , "sex" , "yob" , "citizen" , "msuccess" ,
    "success_exp" , "failed_exp"
]]

In [301]:
df_unificado.head()

,peakid,pkname,heightm,expid,year,season,memid,sex,yob,citizen,msuccess,success_exp,failed_exp
0,AMAD,Ama Dablam,6814,AMAD01101,2001,Spring,2,M,1972.0,Australia,False,1123,453
1,AMAD,Ama Dablam,6814,AMAD01101,2001,Spring,1,M,1968.0,Australia,False,1123,453
2,AMAD,Ama Dablam,6814,AMAD01101,2001,Spring,3,M,1960.0,Australia,False,1123,453
3,AMAD,Ama Dablam,6814,AMAD01101,2001,Spring,4,M,1966.0,Australia,False,1123,453
4,AMAD,Ama Dablam,6814,AMAD01101,2001,Spring,5,F,1970.0,Australia,False,1123,453

### 3.2 Limpieza y transformación (0.2 pts)

Inspeccione y procese su DataFrame para generar uno nuevo llamado `clean_df`. En esta sección usted debe decidir si es necesario:

* Limpiar valores nulos, duplicados o inválidos.
* Imputar valores.
* Transformar tipos de columnas.

Justifique su procesamiento.

In [302]:
#primero analizaremos los datos con info , dtype y describe 

display(df_unificado.info())
print("_"*40)
display(df_unificado.dtypes)
print("_"*40)
display(df_unificado.describe())
print("_"*40)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 89089 entries, 0 to 89088
Data columns (total 13 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   peakid       89089 non-null  object
 1   pkname       89089 non-null  object
 2   heightm      89089 non-null  int64
 3   expid        89089 non-null  object
 4   year         89089 non-null  int64
 5   season       89089 non-null  object
 6   memid        89089 non-null  int64
 7   sex          89089 non-null  object
 8   yob          83665 non-null  float64
 9   citizen      89082 non-null  object
 10  msuccess     89089 non-null  bool
 11  success_exp  89089 non-null  int64
 12  failed_exp   89089 non-null  int64
dtypes: bool(1), float64(1), int64(5), object(6)
memory usage: 8.2+ MB

None

________________________________________

peakid          object
pkname          object
heightm          int64
expid           object
year             int64
season          object
memid            int64
sex             object
yob            float64
citizen         object
msuccess          bool
success_exp      int64
failed_exp       int64
dtype: object

________________________________________

,heightm,year,memid,yob,success_exp,failed_exp
count,89089.000000,89089.000000,89089.000000,83665.000000,89089.000000,89089.000000
mean,7921.765684,2003.426888,7.888381,1966.331154,728.087059,414.098643
std,845.990536,15.716337,8.401750,16.138675,602.811619,317.759808
min,5407.000000,1905.000000,1.000000,1849.000000,0.000000,0.000000
25%,7126.000000,1994.000000,3.000000,1956.000000,130.000000,146.000000
50%,8167.000000,2007.000000,5.000000,1967.000000,861.000000,453.000000
75%,8849.000000,2016.000000,10.000000,1978.000000,1495.000000,852.000000
max,8849.000000,2024.000000,99.000000,2024.000000,1495.000000,852.000000

________________________________________

In [303]:
lista_indices = [
    "peakid" , "pkname" , "heightm" , "expid" , "year" ,
    "season" , "memid" , "sex" , "yob" , "citizen" , "msuccess" ,
    "success_exp" , "failed_exp"
] #si , solo copie lo anterior ;-;

for i in lista_indices:
    null = df_unificado[i].isnull().sum()
    print(f" {i} tiene {null} valores null")
    print("-"*30)

 peakid tiene 0 valores null
------------------------------
 pkname tiene 0 valores null
------------------------------
 heightm tiene 0 valores null
------------------------------
 expid tiene 0 valores null
------------------------------
 year tiene 0 valores null
------------------------------
 season tiene 0 valores null
------------------------------
 memid tiene 0 valores null
------------------------------
 sex tiene 0 valores null
------------------------------
 yob tiene 5424 valores null
------------------------------
 citizen tiene 7 valores null
------------------------------
 msuccess tiene 0 valores null
------------------------------
 success_exp tiene 0 valores null
------------------------------
 failed_exp tiene 0 valores null
------------------------------

podemos ver que yob tiene 5424 valores nulos , esto podria significar tanto duplica de valores como que , censillamente faltaran los datos , veremos esto mismo comparando con el total de datos que tiene yob y su porcentaje para poder tomar una decision

In [304]:
cantidad = (len(df_unificado["yob"]))

print(f"yob tiene la cantidad de {cantidad} datos")
porc = (5424 / cantidad) * 100

print(f"yob tiene un porcentaje de {round(porc, 2)} datos null")

yob tiene la cantidad de 89089 datos
yob tiene un porcentaje de 6.09 datos null

In [305]:
df_unificado[df_unificado["yob"].isnull()].head(10)

,peakid,pkname,heightm,expid,year,season,memid,sex,yob,citizen,msuccess,success_exp,failed_exp
448,EVER,Everest,8849,EVER01131,2001,Spring,26,M,NaN,China,True,1495,852
804,TILI,Tilicho,7134,TILI01101,2001,Spring,7,M,NaN,Nepal,True,31,59
805,TILI,Tilicho,7134,TILI01101,2001,Spring,5,M,NaN,Nepal,True,31,59
806,TILI,Tilicho,7134,TILI01101,2001,Spring,6,M,NaN,Nepal,True,31,59
847,AMAD,Ama Dablam,6814,AMAD01304,2001,Autumn,7,M,NaN,Nepal,True,1123,453
848,AMAD,Ama Dablam,6814,AMAD01304,2001,Autumn,8,M,NaN,Nepal,True,1123,453
855,AMAD,Ama Dablam,6814,AMAD01305,2001,Autumn,7,M,NaN,Nepal,True,1123,453
857,AMAD,Ama Dablam,6814,AMAD01305,2001,Autumn,8,M,NaN,Nepal,True,1123,453
938,AMAD,Ama Dablam,6814,AMAD01317,2001,Autumn,5,M,NaN,Nepal,True,1123,453
939,AMAD,Ama Dablam,6814,AMAD01317,2001,Autumn,4,M,NaN,Nepal,True,1123,453

Podemos ver que , si bien faltan los valores null, el resto de datos estan , es decir, en las columnas se tiene el resto de datos, es por eso que no considero necesario el eliminar los datos, sin embargo, lo que se hara seria, tomando el valor de los datos que contienen tanto yob como citizen, se sustituiran los datos con la moda , ahora bien , podemos notar que hay 7 valores nulos en citizen. estos lo remplazaremos con el pais que mas presencia tiene en el dataframe

In [306]:
ciudadanos = df_unificado["citizen"].mode()[0]
df_unificado.loc[:,"citizen"] = df_unificado["citizen"].fillna(ciudadanos)
print(df_unificado["citizen"].isnull().sum())
#pandas me tiro un "warmning" es por eso que tuve que modificar el codigo con el loc y asi 
#aqui esta la documentacion que lei [https://pandas.pydata.org/docs/user_guide/indexing.html]

0

In [307]:

modas_pais = {}
paises = df_unificado["citizen"].unique()

for pais in paises:
    yob = df_unificado[df_unificado["citizen"] == pais]["yob"].dropna()
    
    if not yob.empty:
        moda = yob.mode()[0]
        modas_pais[pais] = moda
    else:
        print("algo fallo")

for pais , moda in modas_pais.items():
    remplazo = (df_unificado["citizen"] == pais) & (df_unificado["yob"].isnull())
    df_unificado.loc[remplazo, "yob"] = moda
restantes = df_unificado["yob"].isnull().sum()
if restantes > 0:
    print("el proceso fue exitoso , no quedan valores nulos en yob")
    print(f"el proceso fallo en {restantes} valores")
    print(f"se usara la moda general de yob en los {restantes} datos que sobran")
    moda_general = df_unificado["yob"].mode()[0]
    df_unificado.loc[df_unificado["yob"].isnull(), "yob"] = moda_general
    
    
restantes_v2 = df_unificado["yob"].isnull().sum()

print(f"quedaron {restantes_v2} valores nulos en yob")

algo fallo
algo fallo
algo fallo
algo fallo
el proceso fue exitoso , no quedan valores nulos en yob
el proceso fallo en 9 valores
se usara la moda general de yob en los 9 datos que sobran
quedaron 0 valores nulos en yob

In [308]:
for i in lista_indices:
    null = df_unificado[i].isnull().sum()
    print(f" {i} tiene {null} valores null")
    print("-"*30)

 peakid tiene 0 valores null
------------------------------
 pkname tiene 0 valores null
------------------------------
 heightm tiene 0 valores null
------------------------------
 expid tiene 0 valores null
------------------------------
 year tiene 0 valores null
------------------------------
 season tiene 0 valores null
------------------------------
 memid tiene 0 valores null
------------------------------
 sex tiene 0 valores null
------------------------------
 yob tiene 0 valores null
------------------------------
 citizen tiene 0 valores null
------------------------------
 msuccess tiene 0 valores null
------------------------------
 success_exp tiene 0 valores null
------------------------------
 failed_exp tiene 0 valores null
------------------------------

### 3.2 Creación de nuevas columnas (0.6 pts)

Vamos a crear un par de columnas nuevas que nos ayudarán a hacer una análisis exploratorio del dataset.
Utilizando las columnas actuales, genere y agregue las siguientes columnas a su DataFrame:

* `age`: Edad del montañista a la fecha de la expedición.
* `peak_success_p`: Porcentaje de expediciones exitosas de la cima respectiva.

De ser necesario, aplique procesos de limpieza y transformación a estas columnas también (asegúrese de que todos los valores sean coherentes).

In [309]:
# respuestas

## 4. EDA (2.5 puntos)

Con el dataset obtenido, responda las siguientes preguntas. Para cada una de ellas, realice al menos un gráfico que permita visualizar el comportamiento de su dataset.

a. **(0.5 pts)** ¿Cuántos ascensos exitosos y fallidos hay en su dataset? ¿A qué porcentaje del total corresponde cada categoría?

b. **(0.5 pts)** ¿Cómo se distribuyen las edades de los/las montañistas en la base de datos?

c. **(0.5 pts)** ¿Cómo se distribuye la cantidad de ascensos según estación del año? ¿Cuál es el porcentaje de éxito por estación? Muestre la cantidad de filas de ascensos exitosas y fallidas para cada estación.

d. **(0.5 pts)** ¿Cómo cambia la cantidad de ascensos en el tiempo? Muestre la cantidad de ascensos exitosos y fallidos por año.

e. **(0.5 pts)** ¿Existe una correlación entre el porcentaje de éxito de ascenso y la altura de una cumbre? Haga un scatterplot para todas las cumbres que hayan sido escaladas por al menos 10 expediciones en total (tanto fallidas como exitosas).

In [310]:
# respuestas

Respuestas:

## 5. Predictor (2.5 puntos)

Ahora veremos si la información que tenemos nos permite predecir el éxito de un ascenso por alguna persona en particular. Primero, defina su **X** (matriz de atributos) e **y** (etiqueta a predecir) de la siguiente manera:

* **X**: `age`, `sex`, `citizen`, `season`, `heightm`, `year`, `success_exp`, `failed_exp`
* **y**: `msuccess`

Luego, realice los pasos a continuación:

**5.1 Codificación y normalización (1 pto)**
* Codifique todas las columnas categóricas, de manera que su matriz **X** solo tenga valores numéricos.
* Divida sus datos en sets de entrenamiento y testeo. Use una división de 70-30.
* Normalice sus matrices de atributos. Justifique su método de normalización.

**5.2 Creación y entrenamiento de modelos (1 pto)**
* Cree y entrene los siguientes modelos:
    * Un clasificador KNN
    * Un árbol de decisión
    * Un clasificador de regresión logística
    * Un clasificador random forest **(Opcional)**

    Explique qué hiperparámetros utilizó para la creación de cada uno de ellos y qué valores le asignó.

* Finalmente, evalúe todos sus modelos con el set de testeo. Para cada uno, muestre
    * Accuracy
    * Precisión
    * Recall
    * Matriz de confusión

**5.3 Análisis de resultados (0.5 pts)**

Interprete, analice y comente sus resultados. 
* ¿Qué tendencias puede observar? ¿Se diferencian de alguna forma las predicciones entre un modelo y otro? 
* ¿Fue posible construir un predictor efectivo? Justique.

In [311]:
# respuestas

Respuestas: